---
services:
  proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    environment:
       DB_SQLITE_FILE: /data/database.sqlite
       DISABLE_IPV6: 'true'
    volumes:
      - ./data/app:/data
      - ./data/letsencrypt:/etc/letsencrypt
