---
- hosts: localhost
  vars:
    prmgr_db_sqlite_file: /data/database.sqlite
    prmgr_disable_ipv6: true
    prmgr_host_port_proxy_manager_80: 80
    prmgr_host_port_proxy_manager_443: 443
    prmgr_host_port_proxy_manager_81: 81
    prmgr_releases:
      proxy_manager: "latest"

    prmgr_app_mount_dir: "./data/app"
    prmgr_letsencrypt_mount_dir: "./data/letsencrypt"
    # backups
    borgbackup_include:
    - ./data/app
    - ./data/letsencrypt
    # ansible deploy defaults
    docker_deployment_user: dockerusr
    docker_deployment_user_id: 1002
    prmgr_ext_net: proxy-tier
    prmgr_project_name: nginx_proxy_manager
  roles:
  - role: geerlingguy.docker
    tags: docker
  - role: nginx_proxy_manager
    tags: nginx_proxy_manager
