---
role_name_check: 1
dependency:
  name: galaxy
  options:
    roles-path: molecule/default/roles
driver:
  name: docker
platforms:
  - name: "instance-${MOLECULE_DISTRO:-ubuntu2204}-nginx_proxy_manager"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  lint: |
    ansible-lint
  config_options:
    defaults:
      stdout_callback: yaml
      remote_tmp: /tmp/.ansible
