services:
  proxy_manager:
    image: jc21/nginx-proxy-manager:{{ prmgr_releases['proxy_manager'] }}
    container_name: proxy-manager
    restart: unless-stopped
    ports:
    - '{{ prmgr_host_port_proxy_manager_80 }}:80'
    - '{{ prmgr_host_port_proxy_manager_443 }}:443'
    - '{{ prmgr_host_port_proxy_manager_81 }}:81'
    environment:
      DB_SQLITE_FILE: '{{ prmgr_db_sqlite_file }}'
      DISABLE_IPV6: '{{ prmgr_disable_ipv6 }}'
    volumes:
    - '{{ prmgr_app_mount_dir }}:/data'
    - '{{ prmgr_letsencrypt_mount_dir }}:/etc/letsencrypt'
